name = "cadastro-familias-enchente-api"
compatibility_date = "2026-08-18"
main = "worker.js"

[[d1_databases]]
binding = "DB"
database_name = "cadastro-familias-enchente"
database_id = "edce6bac-8679-48b4-aee5-0ad532a57601"
