name = "cadastro-familias-enchente-api"
compatibility_date = "2026-08-18"
main = "worker.js"

[[d1_databases]]
binding = "DB"
database_name = "cadastro-familias-enchente"
database_id = "00000000-0000-0000-0000-000000000000"
